### ISSUE TITLE
Format of numbers written to .inp files

### ISSUE THREAD

**Issue by jpenko** [RossBoylan/mccli#19]
Background: The current version of `montecarlo.py` generates new inputs for interventions by calculating from variables defined in `inp_distribution.txt` and writing new, varied values to `.inp` files (identifying where to write the new input by scanning for text "flags" defined in the `inp_distribution.txt` and the `_mc0.inp` files). 

Problem: The program is writing to the `_mc0.inp` files using a number format (6 digits after the decimal) that is different from that used for the Fortran program (8 digits after the decimal). We'd like to change to writing out 8 digits after the decimal.

**Comment by RossBoylan** [comment]
@jpenko Which numbers should have 8 digits after the decimal?  Anything that is floating point?

And congrats on opening your first issue 😄

**Comment by jpenko** [comment]
Anything that is varied by way of the inp_distribution.txt file. I don't think we have a way of distinguishing separate type of inputs for the .inp file variations (3 total flavors: risk factor changes from interventions, quality of life changes from interventions, and intervention costs), but 8 after the decimal will work for each of them. -j

**Comment by jpenko** [comment]
Exciting development!! Thank you!! -j
